configuration:
  template_dir:
  - "git://github.com/moremoban/pypi-mobans?submodule=true&branch=dev!/templates"
  - "git://github.com/moremoban/pypi-mobans?submodule=true&branch=dev!/statics"
  - ".moban.d"
  configuration: moban-handlebars.yml
targets:
  - README.rst: CUSTOM_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - "docs/source/conf.py": "docs/conf.py_t"
  - test.sh: test.script.jj2
  - "moban_handlebars/_version.py": "_version.py.jj2"
  - .gitignore: gitignore.jj2
  - .travis.yml: custom_travis.yml.jj2
  - Pipfile: Pipfile.jj2
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
  - lint.sh: lint.script.jj2
  - LICENSE: "mit_license.jj2"
  - MANIFEST.in: MANIFEST.in.jj2
  - ".github/workflows/pythonpublish.yml": "pythonpublish.yml"
  - "tests/regression_tests/level-11-helpers-and-partials/README.rst": "level-11-readme.rst.jj2"